### ISSUE TITLE
Simple

### ISSUE THREAD

**Issue by houseless** [MSchmidt/jquery-fullsizable#13]
Your job is awesome and I'm partly new in Jquery world.Just curious about something.

Think a portfolio page which include different galleries e.g "Cars" , "Bikes" , "BlaBla" ,"BlaBla" inside it.When someone click the gallery name , e.g : "Cars",and then viewer shows full-size images without click the thumbs of the images.And next,next,next.. then press close button and turn the portfolio page.

Abstract : how can i do that full-size entrance without click the thumbs?is there any way to enter directly full-size images?

**Comment by MSchmidt** [comment]
2 things to accomplish this:

1. set this option: ``openOnClick: false``
2. ``$(document).trigger('fullsizable:open', '#first-image')`` - replace ``#first-image`` with the selector of the image you'd like to open.
