### ISSUE TITLE
Image height

### ISSUE THREAD

**Issue by tatof** [MSchmidt/jquery-fullsizable#17]
I'm using fullsizable for a product preview, but I would like to change the height of the image or give it a padding of 40px; top/bottom.

When I give it padding with CSS it just go's down and the image will overflow the body/html.
How can I adjust the size to -40px?

thank you,

**Comment by tatof** [comment]
fixed it with: 

-ms-transform: scale(0.8); /\* IE 9 _/
-webkit-transform: scale(0.8); /_ Safari */
transform: scale(0.8);

only don't think this is the best solution...

**Comment by MSchmidt** [comment]
The dimensions of the images itself are set through javascript. You should adjust the padding of `#jquery-fullsizable` for the effect you are after.

``` css
#jquery-fullsizable {
  padding: 40px 0;
}
```

**Comment by tatof** [comment]
Sorry but it seems that the script does set the height/width.. as you can see here:
http://jxerot.com/share/blup.png

and here:
     if ($(window).height() / image.ratio > $(window).width()) {
            $(image).width($(window).width());
            $(image).height($(window).width() \* image.ratio);
            return $(image).css('margin-top', ($(window).height() - $(image).height()) / 2);
        } else {
            $(image).height($(window).height());
            $(image).width($(window).height() / image.ratio);
            return $(image).css('margin-top', 0);  
        }

Your padding solution just gave me padding top & bottom, but the bottom of the images is gone.
Here is my solution (that I hope issnt needed to fix the height/width margin)

http://jxerot.com/share/blup2.png

**Comment by tatof** [comment]
fixed it!  (still with the scale css)

here is a demo: (with many changes)
http://next.logic4.nl/artikel/22368/hamilton-american-classic-spirit-liberty-auto-chrono.html
